import {
  aliasedName,
  publicRoleName,
  publicSystemName,
  type ResolvedDefinition,
  type ResolvedRef,
  type ResolvedRole,
} from "./resolve.js";

function cssVarName(role: ResolvedRole): string {
  return publicRoleName(role, "css", "-");
}

function cssValueFor(resolved: ResolvedDefinition, entry: ResolvedRef): string {
  if (entry.target.kind === "step" && entry.opaque) {
    const system = resolved.systems.find(
      (s) => entry.target.kind !== "role" && s.system === entry.target.system,
    );
    if (system) {
      return `var(--color-${publicSystemName(system, "css")}-${entry.target.selector.replace(".", "_")})`;
    }
  }
  if (entry.target.kind === "role") {
    const target = resolved.roles.find(
      (r) =>
        entry.target.kind === "role" &&
        r.domain === entry.target.domain &&
        r.role === entry.target.role,
    );
    if (target) return `var(--${cssVarName(target)})`;
  }
  // transparent() results and overlay steps have no primitive variable to
  // point at; they inline their computed value.
  return entry.css;
}

export function emitCss(resolved: ResolvedDefinition): string {
  const lines: string[] = [];
  lines.push(
    "/* Generated by dtg from the definition file — do not edit. */",
    "",
    "@theme {",
  );
  for (const system of resolved.systems) {
    const opaqueSteps = system.steps.filter((s) => s.opaque);
    if (opaqueSteps.length === 0) continue;
    const name = publicSystemName(system, "css");
    lines.push(`  /* ${system.system} (${system.algorithm}) */`);
    for (const step of opaqueSteps) {
      lines.push(`  --color-${name}-${step.publicStep}: ${step.css};`);
    }
  }
  if (resolved.statics.length > 0) {
    lines.push("  /* statics */");
    for (const s of resolved.statics) {
      lines.push(`  --color-${s.name}: ${s.hex};`);
    }
  }
  lines.push("}", "");

  resolved.modes.forEach((mode, i) => {
    lines.push(i === 0 ? ":root {" : `.${mode} {`);
    for (const role of resolved.roles) {
      lines.push(
        `  --${cssVarName(role)}: ${cssValueFor(resolved, role.perMode[i])};`,
      );
    }
    lines.push("}", "");
  });

  lines.push(
    "/* Semantic tokens wired into Tailwind utilities */",
    "@theme inline {",
  );
  for (const role of resolved.roles) {
    const name = cssVarName(role);
    lines.push(`  --color-${name}: var(--${name});`);
  }
  lines.push("}");
  return lines.join("\n") + "\n";
}

/**
 * Figma variable payload: a deterministic description of collections,
 * variables, and per-mode values for a courier (agent or future bridge
 * client) to replay via the Plugin API. Sections map to collections;
 * aliases carry the target variable's name; the courier resolves names to
 * Figma ids.
 */
export type FigmaValue =
  | { type: "color"; hex: string }
  | { type: "color"; rgba: string }
  | { type: "alias"; collection: string; variable: string };

export type FigmaPayload = {
  collections: {
    name: string;
    modes: string[];
    variables: {
      name: string;
      description?: string;
      valuesByMode: FigmaValue[];
    }[];
  }[];
};

export function emitFigma(resolved: ResolvedDefinition): FigmaPayload {
  const systemsCollection = aliasedName(
    resolved.systemsAlias,
    "figma",
    "systems",
  );
  const sectionCollection = new Map(
    resolved.sections.map((s) => [
      s.name,
      aliasedName(s.alias, "figma", s.name),
    ]),
  );

  const primitives: FigmaPayload["collections"][number] = {
    name: systemsCollection,
    modes: ["value"],
    variables: [],
  };
  for (const system of resolved.systems) {
    const name = publicSystemName(system, "figma");
    for (const step of system.steps.filter((s) => s.opaque)) {
      primitives.variables.push({
        name: `${name}/${step.publicStep}`,
        description: step.overridden
          ? `${system.system}/${step.selector} (override; algorithm produced ${step.generatedCss})`
          : `${system.system}/${step.selector}`,
        valuesByMode: [{ type: "color", hex: step.css }],
      });
    }
  }
  for (const s of resolved.statics) {
    primitives.variables.push({
      name: `static/${s.name}`,
      valuesByMode: [{ type: "color", hex: s.hex }],
    });
  }

  const collections: FigmaPayload["collections"] = [primitives];
  for (const section of resolved.sections) {
    const collection: FigmaPayload["collections"][number] = {
      name: sectionCollection.get(section.name) ?? section.name,
      modes: resolved.modes,
      variables: [],
    };
    for (const role of resolved.roles.filter(
      (r) => r.section === section.name,
    )) {
      collection.variables.push({
        name: publicRoleName(role, "figma", "/"),
        description: role.perMode
          .map((e, i) => `${resolved.modes[i]}: ${e.ref}`)
          .join(" · "),
        valuesByMode: role.perMode.map((entry): FigmaValue => {
          if (entry.target.kind === "step" && entry.opaque) {
            const system = resolved.systems.find(
              (s) =>
                entry.target.kind !== "role" &&
                s.system === entry.target.system,
            );
            return {
              type: "alias",
              collection: systemsCollection,
              variable: `${system ? publicSystemName(system, "figma") : entry.target.system}/${entry.target.selector.replace(".", "_")}`,
            };
          }
          if (entry.target.kind === "role") {
            const target = resolved.roles.find(
              (r) =>
                entry.target.kind === "role" &&
                r.domain === entry.target.domain &&
                r.role === entry.target.role,
            );
            if (target) {
              return {
                type: "alias",
                collection:
                  sectionCollection.get(target.section) ?? target.section,
                variable: publicRoleName(target, "figma", "/"),
              };
            }
          }
          return { type: "color", rgba: entry.css };
        }),
      });
    }
    collections.push(collection);
  }

  return { collections };
}
